### ISSUE TITLE
[feat] Router, Components, Etc

### ISSUE THREAD

**Issue by ynawhocodes** [countrip/countrip-frontend#6]
## Task
- [x] 모든  branch merge 해서 Router 정리
- [ ] components 추가
- [ ] favicon 추가
- [x] SVG assets 추가

## Detail
**2) common components**
- [ ] RoundInputText
- [x] BottomModal
- [x] Header (content 추가)
- [x] Navigation
- [x] SideModal
  
**2-1) other components**
- [x] Calendar
- [x] HorizontalScrollSquareBoxList
- [ ] SquareBoxItem
